FROM docker.prod.pdc.digital.csaa-insurance.aaa.com/ubuntu-ruby-aws:latest
RUN /bin/bash -l -c "wget -O /usr/local/bin/fly https://github.com/concourse/concourse/releases/download/v3.5.0/fly_linux_amd64"
RUN chmod 755 /usr/local/bin/fly
